export enum Utility {
  AirConditioner = "AIR_CONDITIONER",
  AlmostFull = "ALMOST_FULL",
  BedSeat = "BED_SEAT",
  Blanket = "BLANKET",
  Cancellation = "CANCELLATION",
  EnglishSupported = "ENGLISH_SUPPORTED",
  ETicket = "E_TICKET",
  InstantConfirmation = "INSTANT_CONFIRMATION",
  FreeLuggage = "1_FREE_LUGGAGE",
  Pillow = "PILLOW",
  RestStop = "REST_STOP",
  Wifi = "WIFI",
  Water = "WATER",
  Support247 = "SUPPORT_24_7",
  Outlets = "OUTLETS",
  OnboardEntertainment = "ONBOARD_ENTERTAINMENT",
  MassageSeat = "MASSAGE_SEAT",
  SightSeeing = "SIGHT_SEEING",
  TourGuide = "TOUR_GUIDE",
  SightSeeingTicket = "SIGHT_SEEING_TICKET",
  RecliningSeat = "RECLINING_SEAT",
  Towel = "TOWEL",
  Snacks = "SNACKS",
  RestRoomOnBus = "REST_ROOM_ON_BUS",
  Tv = "TV",
}
